[SYNC]
s3_bucket = s3://jang-ns16001b-cdl-ns16001b-noresminputdata/
nr_workers = 128
log_level = info

[FILES]
 
manifest = /cluster/work/projects/nn9560k/agu002/NorESM23/cases/N1850.ne16pg3_tn14.exp11/case-10.filelist 
